/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AbilityScores: typeof import('./components/sheet/AbilityScores.vue')['default']
    ActionBadge: typeof import('./components/ui/ActionBadge.vue')['default']
    AttacksList: typeof import('./components/sheet/AttacksList.vue')['default']
    CharacterSheet: typeof import('./components/CharacterSheet.vue')['default']
    CombatStats: typeof import('./components/sheet/CombatStats.vue')['default']
    ControlPanel: typeof import('./components/ControlPanel.vue')['default']
    DeathSaves: typeof import('./components/sheet/DeathSaves.vue')['default']
    EquipmentBlock: typeof import('./components/sheet/EquipmentBlock.vue')['default']
    ErrorModal: typeof import('./components/modals/ErrorModal.vue')['default']
    FeatureEditorModal: typeof import('./components/modals/FeatureEditorModal.vue')['default']
    FeaturesList: typeof import('./components/sheet/FeaturesList.vue')['default']
    ImportModal: typeof import('./components/modals/ImportModal.vue')['default']
    InfoButton: typeof import('./components/ui/InfoButton.vue')['default']
    LoadingModal: typeof import('./components/modals/LoadingModal.vue')['default']
    MobileHeader: typeof import('./components/MobileHeader.vue')['default']
    MobileTabBar: typeof import('./components/MobileTabBar.vue')['default']
    PersonalityBlock: typeof import('./components/sheet/PersonalityBlock.vue')['default']
    PrintableSheet: typeof import('./components/sheet/PrintableSheet.vue')['default']
    RenownProgression: typeof import('./components/sheet/RenownProgression.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavingThrows: typeof import('./components/sheet/SavingThrows.vue')['default']
    ShareModal: typeof import('./components/modals/ShareModal.vue')['default']
    SheetControls: typeof import('./components/SheetControls.vue')['default']
    SheetHeader: typeof import('./components/sheet/SheetHeader.vue')['default']
    SkillsList: typeof import('./components/sheet/SkillsList.vue')['default']
    SpellcastingBlock: typeof import('./components/sheet/SpellcastingBlock.vue')['default']
    StartingEquipmentWizard: typeof import('./components/creation/StartingEquipmentWizard.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
    UpdateNotification: typeof import('./components/UpdateNotification.vue')['default']
  }
}

// For TSX support
declare global {
  const AbilityScores: typeof import('./components/sheet/AbilityScores.vue')['default']
  const ActionBadge: typeof import('./components/ui/ActionBadge.vue')['default']
  const AttacksList: typeof import('./components/sheet/AttacksList.vue')['default']
  const CharacterSheet: typeof import('./components/CharacterSheet.vue')['default']
  const CombatStats: typeof import('./components/sheet/CombatStats.vue')['default']
  const ControlPanel: typeof import('./components/ControlPanel.vue')['default']
  const DeathSaves: typeof import('./components/sheet/DeathSaves.vue')['default']
  const EquipmentBlock: typeof import('./components/sheet/EquipmentBlock.vue')['default']
  const ErrorModal: typeof import('./components/modals/ErrorModal.vue')['default']
  const FeatureEditorModal: typeof import('./components/modals/FeatureEditorModal.vue')['default']
  const FeaturesList: typeof import('./components/sheet/FeaturesList.vue')['default']
  const ImportModal: typeof import('./components/modals/ImportModal.vue')['default']
  const InfoButton: typeof import('./components/ui/InfoButton.vue')['default']
  const LoadingModal: typeof import('./components/modals/LoadingModal.vue')['default']
  const MobileHeader: typeof import('./components/MobileHeader.vue')['default']
  const MobileTabBar: typeof import('./components/MobileTabBar.vue')['default']
  const PersonalityBlock: typeof import('./components/sheet/PersonalityBlock.vue')['default']
  const PrintableSheet: typeof import('./components/sheet/PrintableSheet.vue')['default']
  const RenownProgression: typeof import('./components/sheet/RenownProgression.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SavingThrows: typeof import('./components/sheet/SavingThrows.vue')['default']
  const ShareModal: typeof import('./components/modals/ShareModal.vue')['default']
  const SheetControls: typeof import('./components/SheetControls.vue')['default']
  const SheetHeader: typeof import('./components/sheet/SheetHeader.vue')['default']
  const SkillsList: typeof import('./components/sheet/SkillsList.vue')['default']
  const SpellcastingBlock: typeof import('./components/sheet/SpellcastingBlock.vue')['default']
  const StartingEquipmentWizard: typeof import('./components/creation/StartingEquipmentWizard.vue')['default']
  const ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
  const UpdateNotification: typeof import('./components/UpdateNotification.vue')['default']
}